export const FORGOT_PASSWORD_CONSTANTS = {
  CONTAINER_PADDING: 24,
  TITLE_MARGIN_BOTTOM: 32,
  INPUT_MARGIN_BOTTOM: 12,
  ERROR_MARGIN_BOTTOM: 8,
  BUTTON_MARGIN_TOP: 8,
  TEXT_MARGIN_TOP: 20,
  TOAST_SUCCESS_DURATION: 2500,
  TOAST_ERROR_DURATION: 3000,
} as const;

export const FORGOT_PASSWORD_MESSAGES = {
  TITLE: 'Forgot Password',
  EMAIL_PLACEHOLDER: 'Enter your email',
  BUTTON_TEXT: 'Send Reset Link',
  LOGIN_PROMPT: 'Remembered your password?',
  LOGIN_LINK: 'Login',
} as const;