import { ImageBackground } from "react-native";

export const fonts = {
    regular: 'Poppins-Regular',
    semiBold: 'Poppins-SemiBold',
    Bold: 'Poppins-Bold',
    light: 'Poppins-Light',
    blackItalic: 'Poppins-BlackItalic',
    black: 'Poppins-Black',
    italic: 'Poppins-Italic',
    thin: 'Poppins-Thin',
    thinItalic: 'Poppins-ThinItalic',
    extraBold: 'Poppins-ExtraBold',
    extraLight: 'Poppins-ExtraLight',
    extraLightItalic: 'Poppins-ExtraLightItalic',
    extraBoldItalic: 'Poppins-ExtraBoldItalic',
    medium: 'Poppins-Medium',
  };
  
  export const colors = {
    primary: '#007BFF',
    success: '#34C759',
    background: '#ffffff',
    textPrimary: '#000000',
    textSecondary: '#555555',
    text: '#555',
    border: '#ccc',
    inputBackground: '#f9f9f9',
    error: '#FF3B30',
    warning: '#FF9500',
    info: '#007AFF',
    light: '#f0f0f0',
    darkHeader: '#000000',
    lightHeader: '#ffffff',
    darkCard: '#0a0a0a',
    lightCard: '#f9f9f9',
    nameCardDark: '#eee',
    nameCardLight: '#333333',
    priceDark: '#FFD700',   
    darkSearchbar: '#222',
    lightSearchbar: '#f0f0f0',
    darkSearch: '#999',
    lightSearch: '#666',
    notFoundDark: '#888',
    notFoundLight: '#999',
    priceDarkDetails: '#0af',
    lineDark: '#444',
    imageBackground: '#f8f8f8',
    avatarContainerBackground: '#e1e1e1',

  };
  