export const PROFILE_CONSTANTS = {
  CONTAINER_PADDING: 20,
  PROFILE_SECTION_MARGIN: 30,
  IMAGE_MARGIN_BOTTOM: 20,
  NAME_MARGIN_BOTTOM: 5,
  BUTTON_PADDING: 16,
  BUTTON_BORDER_RADIUS: 12,
  LOADING_GAP: 10,
} as const;

export const PROFILE_MESSAGES = {
  NO_NAME_FALLBACK: 'No Name',
  LOGOUT_BUTTON: 'Log Out',
  LOGGING_OUT: 'Logging Out...',
  LOGOUT_ACCESSIBILITY_ACTIVE: 'Logging out',
  LOGOUT_ACCESSIBILITY_IDLE: 'Log out',
} as const;